name: patch-cloud-function
on: [workflow_dispatch]

jobs:
  patch-cloud-function:
    runs-on: ubuntu-latest
    name: Pushes the source code into Google Cloud Storage and Patches a Cloud Function with source code update.
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push Source Code to Cloud Storage and Patch the cloud function
        id: print_env_vars
        uses: KChaitanyaP/github_actions_gcp@v1.1
        with:
          gcp_project: ${{ secrets.GCP_PROJECT }}
          gcp_region: ${{ secrets.GCP_REGION }}
          cloud_function_name: ${{ secrets.CLOUD_FUNCTION_NAME }}
          source_code_directory: ${{ secrets.SOURCE_CODE_DIRECTORY }}
          credentials: ${{ secrets.CREDENTIALS }}

# sample template to be used in any cloud function code for automated update to Google Cloud
# SETUP the SECRETS before using this Github Action
# CREDENTIALS expects a service account with the following roles:
# 1. roles/cloudfunctions.developer
# 2. roles/iam.serviceAccountUser for the particular cloud function runtime service account (more information at https://cloud.google.com/functions/docs/reference/iam/roles#additional-configuration.)